title: The Turing Act
longtitle: "The Turing Act: Regulations for AI/ML self-identification"
description: "Machine Learning has grown up from the last time you saw it. Especially if the last thing you saw was SkyNet."
stinger: "Don't let Machine Learning's tendrils become ever more entwined in our daily lives."
url: "https://turing-act.com"
image: "https://turingact.com/turing-act.png"